import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { Container } from "@/components/ui/container";
import { Breadcrumb } from "@/components/layout/breadcrumb";
import { JsonLd } from "@/components/seo/json-ld";
import { generatePageMetadata } from "@/lib/seo/metadata";
import {
  buildWebPageSchema,
  buildSoftwareAppSchema,
  buildHowToSchema,
  buildFaqSchema,
} from "@/lib/seo/schema";
import { HvacCalculatorForm } from "@/components/tools/hvac-calculator/hvac-form";
import {
  Wind,
  HelpCircle,
  AlertTriangle,
  Scale,
  CheckCircle2,
  ArrowRight,
  Compass,
  Snowflake,
} from "lucide-react";

export const metadata: Metadata = generatePageMetadata({
  title: "HVAC BTU Heating & Cooling Calculator",
  description:
    "Free HVAC BTU calculator for sizing air conditioners, heat pumps, and furnaces. Calculate heating and cooling loads and AC tonnage (1.5 to 5 tons) by climate zone.",
  path: "/hvac/btu-calculator",
  keywords: [
    "hvac btu calculator",
    "btu calculator",
    "ac btu calculator",
    "heating and cooling load calculator",
    "ac tonnage calculator",
    "mini split sizing calculator",
    "how many btu for house",
    "heat pump sizing calculator",
  ],
});

export default function HvacBtuCalculatorPage() {
  const breadcrumbs = [
    { name: "HVAC & Airflow", url: "/categories/hvac" },
    {
      name: "HVAC BTU Heating & Cooling Load Calculator",
      url: "/hvac/btu-calculator",
    },
  ];

  const pageSchema = buildWebPageSchema(
    "HVAC BTU Heating & Cooling Load Calculator",
    "Free HVAC BTU calculator for sizing air conditioners, heat pumps, and furnaces. Calculate heating and cooling loads, AC tonnage (1.5 to 5 tons), and mini-split capacity by climate zone.",
    "/hvac/btu-calculator",
    breadcrumbs
  );

  const softwareAppSchema = buildSoftwareAppSchema({
    name: "HVAC BTU Heating & Cooling Load Estimator",
    description:
      "Trade calculation utility for estimating residential heating and cooling BTU/hr loads, nominal AC tonnage, and mini-split heat pump capacity across US climate zones.",
    url: "/hvac/btu-calculator",
    applicationCategory: "CalculatorApplication",
  });

  const howToSchema = buildHowToSchema(
    "How to Calculate HVAC Heating & Cooling BTU Loads",
    "A comprehensive engineering guide to calculating room and whole-house heating and cooling BTU requirements.",
    [
      {
        name: "Measure Conditioned Floor Area and Ceiling Height",
        text: "Determine the exact square footage and vertical ceiling height of the living space to calculate total conditioned air volume in cubic feet.",
      },
      {
        name: "Identify Your Climate Zone and Design Temperatures",
        text: "Select your local DOE/ASHRAE climate zone to establish the summer cooling temperature difference (ΔT) and winter heating temperature difference.",
      },
      {
        name: "Evaluate Envelope Insulation and Window Glazing",
        text: "Determine the R-values of exterior walls and attic ceilings, along with window U-values and solar heat gain coefficients (SHGC).",
      },
      {
        name: "Account for Internal Heat Gains and Air Leakage",
        text: "Add sensible and latent heat loads from building occupants (430 BTU/person), kitchen appliances (1,200 BTU), and air infiltration.",
      },
      {
        name: "Calculate Tonnage and Equipment Capacity",
        text: "Divide total cooling BTU/hr by 12,000 to determine exact cooling tons, and select the nearest nominal standard equipment size (1.5 to 5.0 tons).",
      },
    ]
  );

  const faqItems = [
    {
      question: "How many BTUs per square foot do I need for heating and cooling?",
      answer:
        "While crude rules of thumb suggest 20 to 30 BTU per square foot for cooling, accurate sizing depends heavily on climate zone, ceiling height, insulation quality, and window solar exposure. A modern well-insulated home in a moderate climate may only require 14 to 18 BTU/sq ft, whereas an older uninsulated home in a hot climate may need 30 to 35 BTU/sq ft.",
    },
    {
      question: "How many tons of air conditioning do I need for my house?",
      answer:
        "One ton of air conditioning equals 12,000 BTU/hr of cooling capacity. A standard 1,800 sq ft home with average insulation in a mixed climate typically requires a 2.5-ton to 3.0-ton AC or heat pump system (30,000 to 36,000 BTU/hr).",
    },
    {
      question: "What is the difference between sensible and latent heat loads?",
      answer:
        "Sensible heat is the heat you can measure with a thermometer (temperature changes from sun, air temperature, and appliances). Latent heat is the moisture and humidity in the air generated by human perspiration, breathing, and humid outdoor air infiltration. Air conditioners must remove both sensible heat to lower temperature and latent heat to dehumidify the space.",
    },
    {
      question: "How does ceiling height affect HVAC sizing?",
      answer:
        "Taller ceilings (9 ft, 10 ft, or 12 ft vaulted ceilings) increase the total volume of air that must be conditioned and increase the gross exterior wall surface area. Every additional foot of ceiling height typically increases heating and cooling load by 8% to 12%.",
    },
    {
      question: "Why is an oversized air conditioner bad for home comfort?",
      answer:
        "An oversized air conditioner cools the house too quickly and shuts off (short-cycling) before it has run long enough to dehumidify the air. This results in cold, clammy rooms, high indoor humidity, poor air filtration, increased wear on compressor components, and higher electric bills.",
    },
    {
      question: "How do I size a ductless mini-split heat pump?",
      answer:
        "Ductless mini-splits are sized on a room-by-room or zone-by-zone basis. Standard mini-split capacities are 9,000 BTU (0.75-ton), 12,000 BTU (1-ton), 18,000 BTU (1.5-ton), 24,000 BTU (2-ton), and 36,000 BTU (3-ton). Multi-zone outdoor compressors can connect to multiple indoor wall heads.",
    },
  ];

  const faqSchema = buildFaqSchema(faqItems);

  return (
    <>
      <JsonLd schema={[pageSchema, softwareAppSchema, howToSchema, faqSchema]} />

      <div className="py-8 sm:py-10 space-y-12">
        <Container>
          {/* Breadcrumbs */}
          <Breadcrumb items={breadcrumbs} />

          {/* Above the Fold: Header & Intro */}
          <div className="space-y-3 mb-8">
            <div className="inline-flex items-center gap-2 rounded-full border border-amber-500/30 bg-amber-500/10 px-3 py-1 text-xs font-semibold text-amber-800">
              <Wind className="h-3.5 w-3.5" />
              HVAC &amp; Airflow Thermal Sizing Utility
            </div>
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight text-slate-900">
              HVAC BTU Heating &amp; Cooling Load Calculator
            </h1>
            <p className="text-base sm:text-lg text-slate-600 max-w-3xl leading-relaxed">
              Calculate heating and cooling BTU/hr loads, nominal <strong>air conditioner tonnage (1.5 to 5.0 Tons)</strong>, and ductless mini-split heat pump capacity based on room dimensions, US climate zones, insulation R-values, and solar heat gains.
            </p>
          </div>

          {/* Interactive Calculator Form Component */}
          <div className="mb-16">
            <HvacCalculatorForm />
          </div>

          {/* Technical Supporting Guide Content */}
          <div className="space-y-12 pt-8 border-t border-slate-200">
            {/* Section 1: Sensible vs Latent Heat */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                <Compass className="h-6 w-6 text-amber-600" />
                1. Understanding Residential HVAC Thermal Loads
              </h2>
              <p className="text-sm sm:text-base text-slate-700 leading-relaxed">
                Proper HVAC equipment sizing requires balancing two distinct forms of thermal energy within the building envelope:
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs sm:text-sm">
                <div className="p-4 rounded-lg bg-white border border-slate-200 shadow-sm space-y-2">
                  <div className="flex items-center gap-2 text-amber-700 font-bold">
                    <Snowflake className="h-4 w-4" />
                    <h3>Sensible Heat Load (Temperature)</h3>
                  </div>
                  <p className="text-slate-600">
                    Thermal energy transferred through exterior walls, attic ceilings, window glass conduction, solar radiation, and air leakage. It directly causes room dry-bulb temperature to rise or fall.
                  </p>
                </div>

                <div className="p-4 rounded-lg bg-white border border-slate-200 shadow-sm space-y-2">
                  <div className="flex items-center gap-2 text-cyan-700 font-bold">
                    <Wind className="h-4 w-4" />
                    <h3>Latent Heat Load (Humidity &amp; Moisture)</h3>
                  </div>
                  <p className="text-slate-600">
                    Moisture vapor introduced by human respiration, perspiration, cooking, showers, and humid outdoor infiltration air. Removing latent heat condenses water on the evaporator coil without changing air temperature.
                  </p>
                </div>
              </div>
            </section>

            {/* Section 2: US Climate Zones and Design Temperatures */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                <Scale className="h-6 w-6 text-amber-600" />
                2. US DOE Climate Zones &amp; Design Temperature Differentials
              </h2>
              <p className="text-sm text-slate-700 leading-relaxed">
                Heating and cooling capacity is governed by the temperature difference between outdoor design extremes and comfortable indoor setpoints (75&deg;F cooling / 70&deg;F heating):
              </p>
              <div className="overflow-x-auto rounded-lg border border-slate-200">
                <table className="w-full text-left text-xs sm:text-sm text-slate-800">
                  <thead className="bg-slate-100 font-bold text-slate-900 border-b border-slate-200">
                    <tr>
                      <th className="p-3">DOE Climate Zone</th>
                      <th className="p-3">Representative Cities</th>
                      <th className="p-3 text-right">Summer Design Temp</th>
                      <th className="p-3 text-right">Winter Design Temp</th>
                      <th className="p-3 text-right">Cooling &Delta;T</th>
                      <th className="p-3 text-right">Heating &Delta;T</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    <tr>
                      <td className="p-3 font-bold text-slate-900">Zone 1 (Very Hot &amp; Humid)</td>
                      <td className="p-3 text-slate-600">Miami, Houston, Honolulu</td>
                      <td className="p-3 text-right font-mono">95&deg;F</td>
                      <td className="p-3 text-right font-mono">48&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-amber-800">+20&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-rose-800">+22&deg;F</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-bold text-slate-900">Zone 2 (Hot &amp; Humid / Dry)</td>
                      <td className="p-3 text-slate-600">Phoenix, Orlando, Tampa</td>
                      <td className="p-3 text-right font-mono">98&deg;F</td>
                      <td className="p-3 text-right font-mono">32&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-amber-800">+23&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-rose-800">+38&deg;F</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-bold text-slate-900">Zone 3 (Warm / Moderate)</td>
                      <td className="p-3 text-slate-600">Atlanta, Dallas, Las Vegas</td>
                      <td className="p-3 text-right font-mono">95&deg;F</td>
                      <td className="p-3 text-right font-mono">22&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-amber-800">+20&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-rose-800">+48&deg;F</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-bold text-slate-900">Zone 4 (Mixed-Humid / Dry)</td>
                      <td className="p-3 text-slate-600">DC, St. Louis, Nashville, Seattle</td>
                      <td className="p-3 text-right font-mono">92&deg;F</td>
                      <td className="p-3 text-right font-mono">12&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-amber-800">+17&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-rose-800">+58&deg;F</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-bold text-slate-900">Zone 5 (Cool / Temperate)</td>
                      <td className="p-3 text-slate-600">Chicago, Denver, Boston</td>
                      <td className="p-3 text-right font-mono">89&deg;F</td>
                      <td className="p-3 text-right font-mono">-2&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-amber-800">+14&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-rose-800">+72&deg;F</td>
                    </tr>
                    <tr>
                      <td className="p-3 font-bold text-slate-900">Zone 6 &amp; 7 (Cold / Subarctic)</td>
                      <td className="p-3 text-slate-600">Minneapolis, Fargo, Duluth</td>
                      <td className="p-3 text-right font-mono">84&deg;F</td>
                      <td className="p-3 text-right font-mono">-24&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-amber-800">+9&deg;F</td>
                      <td className="p-3 text-right font-mono font-bold text-rose-800">+94&deg;F</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>

            {/* Section 3: AC Tonnage Equipment Reference */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                <CheckCircle2 className="h-6 w-6 text-amber-600" />
                3. Standard AC &amp; Heat Pump Tonnage Sizing Matrix
              </h2>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs sm:text-sm">
                <div className="p-3.5 rounded-lg bg-white border border-slate-200 shadow-sm space-y-1">
                  <span className="text-xs font-bold text-amber-700 uppercase block">1.5 Ton AC</span>
                  <h3 className="text-lg font-black text-slate-900">18,000 BTU/hr</h3>
                  <p className="text-slate-600 text-xs">Typical coverage: 600–900 sq ft.</p>
                </div>
                <div className="p-3.5 rounded-lg bg-white border border-slate-200 shadow-sm space-y-1">
                  <span className="text-xs font-bold text-amber-700 uppercase block">2.0 Ton AC</span>
                  <h3 className="text-lg font-black text-slate-900">24,000 BTU/hr</h3>
                  <p className="text-slate-600 text-xs">Typical coverage: 900–1,300 sq ft.</p>
                </div>
                <div className="p-3.5 rounded-lg bg-white border border-slate-200 shadow-sm space-y-1">
                  <span className="text-xs font-bold text-amber-700 uppercase block">2.5 Ton AC</span>
                  <h3 className="text-lg font-black text-slate-900">30,000 BTU/hr</h3>
                  <p className="text-slate-600 text-xs">Typical coverage: 1,300–1,650 sq ft.</p>
                </div>
                <div className="p-3.5 rounded-lg bg-white border border-slate-200 shadow-sm space-y-1">
                  <span className="text-xs font-bold text-amber-700 uppercase block">3.0 Ton AC</span>
                  <h3 className="text-lg font-black text-slate-900">36,000 BTU/hr</h3>
                  <p className="text-slate-600 text-xs">Typical coverage: 1,650–2,100 sq ft.</p>
                </div>
                <div className="p-3.5 rounded-lg bg-white border border-slate-200 shadow-sm space-y-1">
                  <span className="text-xs font-bold text-amber-700 uppercase block">3.5 Ton AC</span>
                  <h3 className="text-lg font-black text-slate-900">42,000 BTU/hr</h3>
                  <p className="text-slate-600 text-xs">Typical coverage: 2,100–2,450 sq ft.</p>
                </div>
                <div className="p-3.5 rounded-lg bg-white border border-slate-200 shadow-sm space-y-1">
                  <span className="text-xs font-bold text-amber-700 uppercase block">4.0 Ton AC</span>
                  <h3 className="text-lg font-black text-slate-900">48,000 BTU/hr</h3>
                  <p className="text-slate-600 text-xs">Typical coverage: 2,450–2,850 sq ft.</p>
                </div>
                <div className="p-3.5 rounded-lg bg-white border border-slate-200 shadow-sm space-y-1">
                  <span className="text-xs font-bold text-amber-700 uppercase block">5.0 Ton AC</span>
                  <h3 className="text-lg font-black text-slate-900">60,000 BTU/hr</h3>
                  <p className="text-slate-600 text-xs">Typical coverage: 2,850–3,500 sq ft.</p>
                </div>
                <div className="p-3.5 rounded-lg bg-amber-50 border border-amber-200 shadow-sm space-y-1">
                  <span className="text-xs font-bold text-amber-800 uppercase block">&gt; 5.0 Tons</span>
                  <h3 className="text-lg font-black text-slate-900">Dual Systems</h3>
                  <p className="text-slate-700 text-xs">Requires multi-zone / dual split units.</p>
                </div>
              </div>
            </section>

            {/* Section 4: Dangers of Oversizing */}
            <section className="space-y-4">
              <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                <AlertTriangle className="h-6 w-6 text-amber-600" />
                4. The Dangers of Oversizing HVAC Equipment (Short-Cycling)
              </h2>
              <div className="bg-amber-50 border border-amber-200 p-4 rounded-lg text-xs sm:text-sm text-amber-950 space-y-2">
                <p className="font-bold text-amber-900">
                  Why &ldquo;Bigger is Not Better&rdquo; in Air Conditioning Sizing
                </p>
                <p className="text-slate-700 leading-relaxed">
                  Homeowners frequently assume that installing a 4-ton or 5-ton AC unit will cool the house faster and better. In practice, oversizing causes severe problems:
                </p>
                <ul className="list-disc pl-5 space-y-1 text-slate-700">
                  <li><strong>Inadequate Dehumidification:</strong> Compressors run for only 5&ndash;8 minutes before shutting off. The coil cools the air quickly but does not run long enough to condense moisture, creating a cold and humid environment.</li>
                  <li><strong>Compressor Wear &amp; Tear:</strong> Frequent on/off starts strain the compressor capacitor and motor, dramatically shortening equipment lifespan.</li>
                  <li><strong>High Electric Utility Bills:</strong> Starting an electric compressor draws 4&times; to 6&times; more current (locked rotor amps) than steady-state running current.</li>
                </ul>
              </div>
            </section>

            {/* Section 5: Reciprocal Trade Ecosystem Cross-Links */}
            <section className="space-y-4 bg-slate-900 text-slate-100 p-6 rounded-xl border border-slate-800">
              <div className="space-y-4">
                <div>
                  <span className="text-xs font-bold uppercase tracking-wider text-amber-400">
                    Interconnected Electrical, HVAC &amp; Construction Ecosystem
                  </span>
                  <h3 className="text-xl font-bold text-white mt-1">
                    Connect HVAC Sizing to Electrical Power &amp; Framing Takeoffs
                  </h3>
                  <p className="text-sm text-slate-300 max-w-3xl">
                    Air conditioning and heat pump installations require dedicated 240V high-amperage electrical branch circuits, weather-resistant conduit raceways, and wall framing accommodations:
                  </p>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2">
                  <Link
                    href="/electrical/voltage-drop-calculator"
                    className="p-4 rounded-lg bg-slate-800 border border-slate-700 hover:border-amber-400 transition-colors group flex flex-col justify-between"
                  >
                    <div>
                      <span className="text-xs font-bold text-amber-400 uppercase tracking-wider block">
                        Electrical Compressor Branch
                      </span>
                      <span className="text-sm font-bold text-white group-hover:text-amber-300">
                        Voltage Drop &amp; Wire Size Calculator
                      </span>
                      <p className="text-xs text-slate-400 pt-0.5">
                        Size 240V copper/aluminum conductors for 30A to 50A condensing units.
                      </p>
                    </div>
                    <div className="flex items-center text-amber-400 text-xs font-bold pt-3 group-hover:translate-x-1 transition-transform">
                      Calculate Wire Size <ArrowRight className="h-4 w-4 ml-1" />
                    </div>
                  </Link>

                  <Link
                    href="/electrical/conduit-fill-calculator"
                    className="p-4 rounded-lg bg-slate-800 border border-slate-700 hover:border-amber-400 transition-colors group flex flex-col justify-between"
                  >
                    <div>
                      <span className="text-xs font-bold text-amber-400 uppercase tracking-wider block">
                        Outdoor Equipment Raceway
                      </span>
                      <span className="text-sm font-bold text-white group-hover:text-amber-300">
                        Electrical Conduit Fill Calculator
                      </span>
                      <p className="text-xs text-slate-400 pt-0.5">
                        Size Liquidtight Flexible Metallic Conduit (LFMC) for outdoor whip connections.
                      </p>
                    </div>
                    <div className="flex items-center text-amber-400 text-xs font-bold pt-3 group-hover:translate-x-1 transition-transform">
                      Calculate Conduit <ArrowRight className="h-4 w-4 ml-1" />
                    </div>
                  </Link>

                  <Link
                    href="/construction/roof-pitch-calculator"
                    className="p-4 rounded-lg bg-slate-800 border border-slate-700 hover:border-amber-400 transition-colors group flex flex-col justify-between"
                  >
                    <div>
                      <span className="text-xs font-bold text-amber-400 uppercase tracking-wider block">
                        Attic Thermal Ventilation
                      </span>
                      <span className="text-sm font-bold text-white group-hover:text-amber-300">
                        Roof Pitch &amp; Rafter Calculator
                      </span>
                      <p className="text-xs text-slate-400 pt-0.5">
                        Calculate roof surface areas and evaluate attic solar heat gain.
                      </p>
                    </div>
                    <div className="flex items-center text-amber-400 text-xs font-bold pt-3 group-hover:translate-x-1 transition-transform">
                      Calculate Roof Pitch <ArrowRight className="h-4 w-4 ml-1" />
                    </div>
                  </Link>
                </div>
              </div>
            </section>

            {/* Section 6: Frequently Asked Questions */}
            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                <HelpCircle className="h-6 w-6 text-amber-600" />
                6. Frequently Asked Questions
              </h2>
              <div className="space-y-4">
                {faqItems.map((faq, idx) => (
                  <div
                    key={idx}
                    className="p-5 rounded-lg border border-slate-200 bg-white space-y-2 shadow-sm"
                  >
                    <h3 className="text-base font-bold text-slate-900">
                      {faq.question}
                    </h3>
                    <p className="text-sm text-slate-600 leading-relaxed">
                      {faq.answer}
                    </p>
                  </div>
                ))}
              </div>
            </section>
          </div>
        </Container>
      </div>
    </>
  );
}
